In [71]:
import torch
print(torch.__version__)

2.9.0+cu126


In [72]:
if torch.cuda.is_available():
    print("CUDA is available. GPU can be used.")
else:
    print("CUDA is not available. Using CPU.")

CUDA is available. GPU can be used.


In [73]:
a = torch.empty(2,3)
print(a)

tensor([[ 1.5512e-04,  0.0000e+00, -1.4578e+27],
        [ 4.5146e-41,  8.9683e-44,  0.0000e+00]])


In [75]:
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]], dtype=torch.float32)
print(x.dtype)
print(x)


torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [76]:
x.dtype

torch.float32

In [77]:
# Creating similar tensors with different data types
x_float = torch.tensor([[1.0, 2.0, 3.0],
                        [4.0, 5.0, 6.0]], dtype=torch.float32)
print(x_float)
print(x_float.dtype)   

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float32


In [78]:
# Creating similar tensors 
# Creating similar tensors 
y = torch.rand_like(x_float)

In [79]:
print(x + y)
print(y + x)

tensor([[1.6381, 2.4652, 3.1051],
        [4.3351, 5.6922, 6.6466]])
tensor([[1.6381, 2.4652, 3.1051],
        [4.3351, 5.6922, 6.6466]])


In [80]:
x * 100 // 3

tensor([[ 33.,  66., 100.],
        [133., 166., 200.]])

In [81]:
d = torch.matmul(x_float, y.T)
d.T

tensor([[1.8839, 5.5093],
        [3.6594, 8.6812]])

In [82]:
d

tensor([[1.8839, 3.6594],
        [5.5093, 8.6812]])

In [83]:
torch.sigmoid(d)

tensor([[0.8681, 0.9749],
        [0.9960, 0.9998]])

In [84]:
torch.relu(d)

tensor([[1.8839, 3.6594],
        [5.5093, 8.6812]])

In [91]:
a = x.clone()
a[0][0] = 999
print(a)
print(x)

tensor([[999.,   2.,   3.],
        [  4.,   5.,   6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [92]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")


In [94]:
a = torch.rand((9, 10000), device=device)
a

tensor([[0.8649, 0.0751, 0.9925,  ..., 0.9468, 0.4422, 0.9884],
        [0.3761, 0.9314, 0.7206,  ..., 0.3659, 0.9898, 0.9051],
        [0.7720, 0.4728, 0.0517,  ..., 0.1242, 0.8991, 0.1924],
        ...,
        [0.7605, 0.9735, 0.5409,  ..., 0.0751, 0.5085, 0.9739],
        [0.5688, 0.2023, 0.2049,  ..., 0.2924, 0.9535, 0.4719],
        [0.4022, 0.1030, 0.5251,  ..., 0.0942, 0.5788, 0.5349]],
       device='cuda:0')

In [ ]:
import time
 
# Create tensors on CPU
a_cpu = torch.rand((10000, 10000))
b_cpu = torch.rand((10000, 10000))
 
# Measure time for CPU multiplication
start_cpu = time.time()
result_cpu = torch.matmul(a_cpu, b_cpu)
end_cpu = time.time()
print(f"CPU multiplication time: {end_cpu - start_cpu} seconds")
 
# Create tensors on GPU
a_gpu = torch.rand((10000, 10000), device='cuda')
b_gpu = torch.rand((10000, 10000), device='cuda')
 
# Measure time for GPU multiplication
start_gpu = time.time()
result_gpu = torch.matmul(a_gpu, b_gpu)
end_gpu = time.time()
print(f"GPU multiplication time: {end_gpu - start_gpu} seconds")